name: Java Manual CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create output directory
        run: mkdir -p out

      - name: Compile tests
        run: |
          javac -cp libs/junit-platform-console-standalone-1.10.0.jar \
            -d out $(find src/test/java -name "*.java")

      - name: Run tests
        run: |
          java -jar libs/junit-platform-console-standalone-1.10.0.jar \
            --class-path out --scan-class-path
