name: Java Manual CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List Java files
        run: find src/test/java/org/example -name "*.java"

      - name: Compile Java files
        run: javac -cp ./lib/junit-platform-console-standalone-1.10.0.jar -d out $(find src/test/java/org/example -name "*.java")

      - name: Run tests
        run: java -jar ./lib/junit-platform-console-standalone-1.10.0.jar -cp out --scan-classpath
